In [0]:
import torch

In [0]:
w = torch.tensor(2.0,requires_grad=True)
b = torch.tensor(-1.0, requires_grad=True)

In [0]:
def forward(x):
  yhat = w * x + b
  return yhat

In [4]:
x = torch.tensor([[1.0]])
yhat = forward(x)
print("The prediction: ",yhat)

The prediction:  tensor([[1.]], grad_fn=<AddBackward0>)


In [5]:
x = torch.tensor([[1.0],[2.0]])
yhat = forward(x)
print("The prediction: ",yhat)

The prediction:  tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


In [6]:
x = torch.tensor([[1.0],[2.0],[3.0]])
yhat = forward(x)
print("The prediction: ",yhat)

The prediction:  tensor([[1.],
        [3.],
        [5.]], grad_fn=<AddBackward0>)


In [0]:
from torch.nn import Linear

In [8]:
torch.manual_seed(1)

In [14]:
lr = Linear(in_features=1,out_features=1,bias=True)
print("Parameters w and b: ",list(lr.parameters()))

Parameters w and b:  [Parameter containing:
tensor([[0.1390]], requires_grad=True), Parameter containing:
tensor([-0.1224], requires_grad=True)]


In [18]:
x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ",yhat)

The prediction:  tensor([[0.0166]], grad_fn=<AddmmBackward>)


In [19]:
x = torch.tensor([[1.0],[2.0]])
yhat = lr(x)
print("The prediction: ",yhat)

The prediction:  tensor([[0.0166],
        [0.1556]], grad_fn=<AddmmBackward>)


In [20]:
x = torch.tensor([[1.0],[2.0],[3.0]])
yhat = lr(x)
print("The prediction: ",yhat)

The prediction:  tensor([[0.0166],
        [0.1556],
        [0.2946]], grad_fn=<AddmmBackward>)


In [0]:
from torch import nn

In [0]:
class LR(nn.Module):
  def __init__(self,input_size,output_size):
    super(LR,self).__init__()
    self.linear = nn.Linear(input_size,output_size)
  
  def forward(self,x):
    out = self.linear(x)
    return out

In [23]:
lr = LR(1,1)
print("The Parameters: ",list(lr.parameters()))
print("Linear model: ",lr.linear)

The Parameters:  [Parameter containing:
tensor([[0.2774]], requires_grad=True), Parameter containing:
tensor([0.0493], requires_grad=True)]
Linear model:  Linear(in_features=1, out_features=1, bias=True)


In [24]:
x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ",yhat)

The prediction:  tensor([[0.3267]], grad_fn=<AddmmBackward>)


In [25]:
x = torch.tensor([[1.0],[2.0],[3.0]])
yhat = lr(x)
print("The prediction: ",yhat)

The prediction:  tensor([[0.3267],
        [0.6041],
        [0.8814]], grad_fn=<AddmmBackward>)
